# Generated by Django 5.0 on 2025-05-22 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_vocabulary_favoritevocabulary'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='category',
            field=models.CharField(choices=[('grammar', 'Grammar'), ('vocabulary', 'Vocabulary'), ('reading', 'Reading Comprehension'), ('listening', 'Listening Comprehension'), ('general', 'General English')], default='general', max_length=50),
        ),
        migrations.AddField(
            model_name='quiz',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='quiz',
            name='pass_mark',
            field=models.IntegerField(default=60, help_text='Percentage score needed to pass'),
        ),
        migrations.AddField(
            model_name='quiz',
            name='time_limit',
            field=models.IntegerField(default=600, help_text='Time limit in seconds (default: 10 minutes)'),
        ),
    ]
