# Generated by Django 5.0 on 2025-05-22 15:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_quiz_category_quiz_is_active_quiz_pass_mark_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='quizquestion',
            name='audio_file',
            field=models.FileField(blank=True, null=True, upload_to='quiz_audio/'),
        ),
        migrations.CreateModel(
            name='QuizProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('grammar', 'Grammar'), ('vocabulary', 'Vocabulary'), ('reading', 'Reading Comprehension'), ('listening', 'Listening Comprehension'), ('general', 'General English')], max_length=50)),
                ('total_attempted', models.IntegerField(default=0)),
                ('total_completed', models.IntegerField(default=0)),
                ('average_score', models.FloatField(default=0)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quiz_progress', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'category')},
            },
        ),
    ]
