# Generated by Django 5.0 on 2025-06-04 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_quizquestion_audio_file_quizprogress'),
    ]

    operations = [
        migrations.AddField(
            model_name='savedword',
            name='audio',
            field=models.FileField(blank=True, null=True, upload_to='vocabulary_audio/'),
        ),
        migrations.AddField(
            model_name='savedword',
            name='level',
            field=models.CharField(blank=True, choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='savedword',
            name='part_of_speech',
            field=models.CharField(blank=True, choices=[('noun', 'Noun'), ('verb', 'Verb'), ('adjective', 'Adjective'), ('adverb', 'Adverb'), ('pronoun', 'Pronoun'), ('preposition', 'Preposition'), ('conjunction', 'Conjunction'), ('interjection', 'Interjection'), ('determiner', 'Determiner')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='savedword',
            name='pronunciation',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='savedword',
            name='synonyms',
            field=models.TextField(blank=True, help_text='Comma-separated synonyms', null=True),
        ),
        migrations.AddField(
            model_name='savedword',
            name='topic',
            field=models.CharField(blank=True, choices=[('business', 'Business'), ('sport', 'Sport'), ('politics', 'Politics'), ('technology', 'Technology'), ('education', 'Education'), ('health', 'Health'), ('entertainment', 'Entertainment'), ('science', 'Science'), ('travel', 'Travel'), ('food', 'Food'), ('other', 'Other')], max_length=100, null=True),
        ),
    ]
