# Generated by Django 5.0 on 2025-06-05 09:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_mocktestresult'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mocktestresult',
            options={},
        ),
        migrations.RemoveField(
            model_name='mocktestresult',
            name='details',
        ),
        migrations.AddField(
            model_name='mocktestresult',
            name='user_answers',
            field=models.TextField(default='{}'),
        ),
        migrations.AlterField(
            model_name='mocktestresult',
            name='correct_answers',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='mocktestresult',
            name='level_achieved',
            field=models.CharField(default='A1', max_length=5),
        ),
        migrations.AlterField(
            model_name='mocktestresult',
            name='score',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='mocktestresult',
            name='test_type',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='mocktestresult',
            name='topic',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='mocktestresult',
            name='total_questions',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='mocktestresult',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
